config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'regions#index'

  mount Sidekiq::Web => '/sidekiq', :constraints => AdminRouteConstraint.new

  # Confusingly, the ids that are passed in to identify
  # regions are the id values present in the multiregion
  # file: https://regions.onebusaway.org/regions-v3.json
  # These values are referred to as `region_identifier`.
  #
  # The ids that exist locally, in Rails's DB, are
  # more or less unused.

  resources :alert_feeds, only: [:show]

  namespace :api do
    namespace :v1 do
      # PaymentIntents (Stripe SDK)
      resources :payment_intents, only: [:create]

      resources :regions, only: [:index] do
        get 'vehicles', on: :member, defaults: {format: 'json'}

        # Weather
        resource :weather, only: [:show]

        # Stop Redirect/Trip Status
        resources :stops, only: [:show] do
          get 'trips'
        end

        # Alarms
        resources :alarms, only: [:create, :destroy]

        # Alerts
        resources :alerts, only: [:index], defaults: {format: 'pb'}

        # Surveys
        resources :surveys, only: [:index]
      end

      resources :survey_responses, only: [:create, :update] do
        post :update, on: :member
      end
    end
  end

  resource :admin, only: [:show, :update] do
    scope module: 'admins' do
      resources :alarms, only: [:index, :show]
      resources :alerts
      resource :redis, only: [:show]
      resources :studies do
        resources :surveys do
          resources :questions
          resources :survey_responses, only: [:index, :show]
        end
      end
    end

    get 'activate', on: :member
    get 'reset_password', on: :member
    get 'alerts', on: :member
  end

  resources :alert_feed_items

  get 'manage-donations', to: 'donations#index'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'

  # Old, unversioned API+HTML
  resources :regions, only: [:index, :show] do
    get 'agencies', on: :member
    get 'validate', on: :member

    resources :alert_feeds, only: [:index]
    resources :alert_feed_items, only: [:index] do
      get 'items', on: :collection
    end
    resources :stops, only: [:show] do
      get 'trips'
    end
    resources :alarms, only: [:create, :destroy]
  end
end

app/views/admins/_survey_tabs.html.erb
<% sub_tab(name: "Designer", path: admin_study_survey_path(@survey.study, @survey)) %>
<% sub_tab(name: "Responses", path: admin_study_survey_survey_responses_path(@survey.study, @survey)) %>

app/views/admins/alarms.html.haml
.col
  .row
    %table.table.table-striped.table-sm
      %thead
        %tr
          %th ID
          %th Region
          %th Push ID/Message
          %th Stop ID
          %th Trip ID
          %th Service Date
          %th Vehicle ID
          %th Stop Sequence
          %th Created At
      %tbody
        - @alarms.each do |a|
          %tr
            %td= a.id
            %td= a.region.name
            %td
              = a.message
              %br
              = a.push_identifier
            %td= a.stop_id
            %td= a.trip_id
            %td= Time.at(a.service_date / 1000.0).strftime("%m-%d-%Y")
            %td= value_or_blank_rep(a.vehicle_id)
            %td= a.stop_sequence
            %td= local_time a.created_at

app/views/admins/alerts.html.haml
= render 'alert_feed_items/items'

app/views/admins/new_session.html.haml
- title "Log In"

%h1 Log In
= form_for :session, url: admin_login_path do |f|
  = f.label :email
  = f.email_field :email, class: 'form-control'

  = f.label :password
  = f.password_field :password, class: 'form-control'

  = f.submit "Log in", class: "btn btn-primary"

app/views/admins/reset_password.html.haml
- title "Reset Password"

= form_for @admin, url: admin_path do |f|
  = f.label :password
  = f.password_field :password, class: 'form-control'
  = f.label :password_confirmation
  = f.password_field :password_confirmation, class: 'form-control'
  = f.submit "Update Password"

app/views/admins/show.html.erb
<% title("#{@region.name} Admin") %>

<%= render Containers::SideTabsComponent.new do |c| %>
  <%= render Admin::SideTabsComponent.new(context: c, current_path: request.fullpath) %>

  <% if @manual_feed.nil? %>
    <p>
      There is no manual feed for this region.
    </p>
  <% else %>
    <p>
      Add an item to the manual feed:
    </p>
    <%= render 'alert_feed_items/form', alert_feed_item: @alert_feed_item %>
  <% end %>

<% end %>