config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'regions#index'

  mount Sidekiq::Web => '/sidekiq', :constraints => AdminRouteConstraint.new

  # Confusingly, the ids that are passed in to identify
  # regions are the id values present in the multiregion
  # file: https://regions.onebusaway.org/regions-v3.json
  # These values are referred to as `region_identifier`.
  #
  # The ids that exist locally, in Rails's DB, are
  # more or less unused.

  resources :alert_feeds, only: [:show]

  namespace :api do
    namespace :v1 do
      # PaymentIntents (Stripe SDK)
      resources :payment_intents, only: [:create]

      resources :regions, only: [:index] do
        get 'vehicles', on: :member, defaults: {format: 'json'}

        # Weather
        resource :weather, only: [:show]

        # Stop Redirect/Trip Status
        resources :stops, only: [:show] do
          get 'trips'
        end

        # Alarms
        resources :alarms, only: [:create, :destroy]

        # Alerts
        resources :alerts, only: [:index], defaults: {format: 'pb'}

        # Surveys
        resources :surveys, only: [:index]
      end

      resources :survey_responses, only: [:create, :update] do
        post :update, on: :member
      end
    end
  end

  resource :admin, only: [:show, :update] do
    scope module: 'admins' do
      resources :alarms, only: [:index, :show]
      resources :alerts
      resource :redis, only: [:show]
      resources :studies do
        resources :surveys do
          resources :questions
          resources :survey_responses, only: [:index, :show]
        end
      end
    end

    get 'activate', on: :member
    get 'reset_password', on: :member
    get 'alerts', on: :member
  end

  resources :alert_feed_items

  get 'manage-donations', to: 'donations#index'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'

  # Old, unversioned API+HTML
  resources :regions, only: [:index, :show] do
    get 'agencies', on: :member
    get 'validate', on: :member

    resources :alert_feeds, only: [:index]
    resources :alert_feed_items, only: [:index] do
      get 'items', on: :collection
    end
    resources :stops, only: [:show] do
      get 'trips'
    end
    resources :alarms, only: [:create, :destroy]
  end
end

app/models/alert_feed_item.rb
require_relative '../protobuf/gtfs-realtime.pb.rb'

class AlertFeedItem < ApplicationRecord
  belongs_to :alert_feed
  delegate :region, to: :alert_feed

  default_scope { order(starts_at: :desc) }

  # Severity names and values are from an extension to GTFS-RT.
  SEVERITY_UNKNOWN = 1
  SEVERITY_INFO = 2
  SEVERITY_WARNING = 3
  SEVERITY_SEVERE = 4

  ###########
  # Cause
  ###########

  CAUSES = [
    [:unknown, TransitRealtime::Alert::Cause::UNKNOWN_CAUSE],
    [:other, TransitRealtime::Alert::Cause::OTHER_CAUSE],
    [:technical_problem, TransitRealtime::Alert::Cause::TECHNICAL_PROBLEM],
    [:strike, TransitRealtime::Alert::Cause::STRIKE],
    [:demonstration, TransitRealtime::Alert::Cause::DEMONSTRATION],
    [:accident, TransitRealtime::Alert::Cause::ACCIDENT],
    [:holiday, TransitRealtime::Alert::Cause::HOLIDAY],
    [:weather, TransitRealtime::Alert::Cause::WEATHER],
    [:maintenance, TransitRealtime::Alert::Cause::MAINTENANCE],
    [:construction, TransitRealtime::Alert::Cause::CONSTRUCTION],
    [:police_activity, TransitRealtime::Alert::Cause::POLICE_ACTIVITY],
    [:medical_emergency, TransitRealtime::Alert::Cause::MEDICAL_EMERGENCY]
  ].freeze

  def gtfs_cause
    CAUSES.each do |sym, gtfs_val|
      return gtfs_val if sym == cause
    end

    TransitRealtime::Alert::Cause::UNKNOWN_CAUSE
  end

  enum :cause, CAUSES.collect(&:first)

  ###########
  # Effect
  ###########

  EFFECTS = [
    [:no_service, TransitRealtime::Alert::Effect::NO_SERVICE],
    [:reduced_service, TransitRealtime::Alert::Effect::REDUCED_SERVICE],
    [:significant_delays, TransitRealtime::Alert::Effect::SIGNIFICANT_DELAYS],
    [:detour, TransitRealtime::Alert::Effect::DETOUR],
    [:additional_service, TransitRealtime::Alert::Effect::ADDITIONAL_SERVICE],
    [:modified_service, TransitRealtime::Alert::Effect::MODIFIED_SERVICE],
    [:other_effect, TransitRealtime::Alert::Effect::OTHER_EFFECT],
    [:unknown_effect, TransitRealtime::Alert::Effect::UNKNOWN_EFFECT],
    [:stop_moved, TransitRealtime::Alert::Effect::STOP_MOVED]
  ].freeze

  enum :effect, EFFECTS.collect(&:first)

  def gtfs_effect
    EFFECTS.each do |sym, gtfs_val|
      return gtfs_val if sym == effect
    end

    TransitRealtime::Alert::Effect::UNKNOWN_EFFECT
  end

  #######

  # [
  #   :no_service,         # 0
  #   :reduced_service,    # 1
  #   :significant_delays, # 2
  #   :detour,             # 3
  #   :additional_service, # 4
  #   :modified_service,   # 5
  #   :other_effect,       # 6
  #   :unknown_effect,     # 7
  #   :stop_moved          # 8
  # ]

  # [
  #     :unknown,            # 0
  #     :other,              # 1
  #     :technical_problem,  # 2
  #     :strike,             # 3
  #     :demonstration,      # 4
  #     :accident,           # 5
  #     :holiday,            # 6
  #     :weather,            # 7
  #     :maintenance,        # 8
  #     :construction,       # 9
  #     :police_activity,    # 10
  #     :medical_emergency   # 11
  #    ]
end

app/controllers/alert_feed_items_controller.rb
class AlertFeedItemsController < ApplicationController
  include AlertFeedItemsConcerns
  before_action :admin_required, except: [:index, :items]

  def index
    # # :-\ this is the result of a dumb decision i made here:
    # # https://github.com/OneBusAway/onebusaway-deep-links/commit/8df90ceb7367e78ebe489421ac268b663dca69d9
    # # now I need to hack around it by keeping this action as-is for backwards compatibility reasons for now.
    # request.format = :json
    #
    # @region = Region.find_by!(region_identifier: params[:region_id])
    # @items = load_index_data(@region, true)
    #
    # respond_to do |format|
    #   format.json
    # end

    render json: []
  end

  def items
    @region = Region.find_by!(region_identifier: params[:region_id])
    @items = load_index_data(@region)
  end

  def create
    @manual_feed = current_admin.region.manual_feed

    if @manual_feed.nil?
      redirect_to admin_path, error: "No manual feed has been created for #{current_admin.region.name} yet"
      return
    end

    # Create the item
    item = @manual_feed.alert_feed_items.build(permitted_params)
    item.external_id  = item.url
    item.starts_at    = DateTime.now
    item.severity     = AlertFeedItem::SEVERITY_WARNING
    item.save!

    # Poke the record's 'updated at' timestamp
    @manual_feed.fetch()

    # @manual_feed.add_alert_item(permitted_params[:title], permitted_params[:summary], permitted_params[:url], params[:test_item])

    redirect_to admin_alerts_path, notice: "Added alert to manual feed."
  end

  def edit
    @item = AlertFeedItem.find(params[:id])
  end

  def update
    @item = AlertFeedItem.find(params[:id])
    if @item.update_attributes(permitted_params)
      redirect_to admin_alerts_path, note: "Updated alert feed item: #{@item.title}."
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    @item = AlertFeedItem.find(params[:id])
    @item.destroy
    redirect_to admin_alerts_path, note: "Deleted alert feed item: #{@item.title}."
  end

  protected

  def permitted_params
    params.require(:alert_feed_item).permit(:title, :summary, :url, :cause, :effect, :test_item)
  end
end

app/views/alert_feed_items/_form.html.erb
<%= form_for alert_feed_item do |f| %>
  <div class='space-y-4'>
    <%= render Forms::TextFieldComponent.new(
      form: f,
      method: :title,
      placeholder: "Salmon Truck Overturned on I-5",
      autofocus: true
    ) %>

    <%= render Forms::TextFieldComponent.new(
      form: f,
      method: :url,
      placeholder: "https://soundtransit.org/news/salmon-truck"
    ) %>

    <%= render Forms::TextAreaComponent.new(
      form: f,
      method: :summary,
      placeholder: "A truck carrying 10,000 pounds of salmon overturned on I-5 this morning. Expect delays."
    ) %>

    <%= render Forms::SelectComponent.new(
      form: f,
      method: :cause,
      collection: AlertFeedItem.causes.keys.map { |k| [k.humanize, k] }
    ) %>

    <%= render Forms::SelectComponent.new(
      form: f,
      method: :effect,
      collection: AlertFeedItem.effects.keys.map { |k| [k.humanize, k] }
    ) %>

    <%= render Forms::CheckboxComponent.new(
      form: f,
      method: :test_item,
      help_text: "Test items are only visible to test app users. Uncheck this box to send the item out to all of your users."
    ) %>

    <div class="mt-6 flex items-center justify-end gap-x-6">
      <%= link_to "Cancel", :back, class: 'oba-btn' %>
      <button type="submit" class="oba-btn--primary">Save</button>
    </div>
  </div>
<% end %>

app/views/alert_feed_items/_items.html.erb
<% if @items.blank? %>
  <%= render Containers::EmptyStateComponent.new(title: "No Alerts", description: "There are no alerts published from our known sources at this time.") %>
<% else %>
  <%= render Tables::TableComponent.new do |c| %>
    <% c.with_column("Title") %>
    <% c.with_column("Feed/ID") %>
    <% c.with_column("Severity") %>
    <% c.with_column("Summary") %>
    <% c.with_column("URL") %>
    <% c.with_column("Starts At") %>
    <% c.with_column("Ends At") %>

    <% if admin_logged_in? %>
      <% c.with_column("Actions") %>
    <% end %>

    <% c.with_tbody do %>
      <% @items.each do |i| %>
        <tr>
          <td class="oba-td">
            <%= i.title %>
            <% if i.test_item %>
              <br>
              <strong>TEST MODE</strong>
            <% end %>
          </td>
          <td class="oba-td">
            <div><%= i.alert_feed.name %></div>
            <div><%= i.external_id %></div>
          </td>
          <td class="oba-td">
            <%= severity_to_string(i.severity) %>
          </td>
          <td class="oba-td">
            <%= truncate(i.summary, length: 500) %>
          </td>
          <td class="oba-td">
            <%= link_to i.url, i.url %>
          </td>
          <td class="oba-td">
            <%= i.starts_at.strftime("%D %I:%M %p") %>
          </td>
          <td class="oba-td">
            <% if i.ends_at %>
              <%= i.ends_at.strftime("%D %I:%M %p") %>
            <% else %>
              —
            <% end %>
          </td>
          <% if admin_logged_in? %>
            <td class="oba-td">
              <%= link_to 'Edit Alert', edit_alert_feed_item_path(i), class: 'oba-btn--primary oba-btn--sm' %>
              <%= button_to 'Delete Alert', i, method: :delete, form: {data: {turbo_confirm: "Are you sure you want to delete this?"}}, class: 'oba-btn--danger oba-btn--sm' %>
            </td>
          <% end %>
        </tr>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/alert_feed_items/edit.html.erb
<%= render 'alert_feed_items/form', alert_feed_item: @item %>

app/views/alert_feed_items/items.html.erb
<% title "Alert Feed Items - #{@region.name}" %>

<%= render Containers::SideTabsComponent.new do |c| %>
  <%= render Regions::SideTabsComponent.new(@region, context: c, current_path: request.fullpath) %>
  <%= render 'alert_feed_items/items' %>
<% end %>