config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  get "up" => "rails/health#show", as: :rails_health_check

  root to: 'regions#index'

  mount Sidekiq::Web => '/sidekiq', :constraints => AdminRouteConstraint.new

  # Confusingly, the ids that are passed in to identify
  # regions are the id values present in the multiregion
  # file: https://regions.onebusaway.org/regions-v3.json
  # These values are referred to as `region_identifier`.
  #
  # The ids that exist locally, in Rails's DB, are
  # more or less unused.

  resources :alert_feeds, only: [:show]

  namespace :api do
    namespace :v1 do
      # PaymentIntents (Stripe SDK)
      resources :payment_intents, only: [:create]

      resources :regions, only: [:index] do
        get 'vehicles', on: :member, defaults: {format: 'json'}

        # Weather
        resource :weather, only: [:show]

        # Stop Redirect/Trip Status
        resources :stops, only: [:show] do
          get 'trips'
        end

        # Alarms
        resources :alarms, only: [:create, :destroy]

        # Alerts
        resources :alerts, only: [:index], defaults: {format: 'pb'}

        # Surveys
        resources :surveys, only: [:index]
      end

      resources :survey_responses, only: [:create, :update] do
        post :update, on: :member
      end
    end
  end

  resource :admin, only: [:show, :update] do
    scope module: 'admins' do
      resources :alarms, only: [:index, :show]
      resources :alerts
      resource :redis, only: [:show]
      resources :studies do
        resources :surveys do
          resources :questions
          resources :survey_responses, only: [:index, :show]
        end
      end
    end

    get 'activate', on: :member
    get 'reset_password', on: :member
    get 'alerts', on: :member
  end

  resources :alert_feed_items

  get 'manage-donations', to: 'donations#index'

  # Sessions
  get    '/login',   to: 'sessions#new'
  post   '/login',   to: 'sessions#create'
  get    '/logout',  to: 'sessions#destroy'

  # Old, unversioned API+HTML
  resources :regions, only: [:index, :show] do
    get 'agencies', on: :member
    get 'validate', on: :member

    resources :alert_feeds, only: [:index]
    resources :alert_feed_items, only: [:index] do
      get 'items', on: :collection
    end
    resources :stops, only: [:show] do
      get 'trips'
    end
    resources :alarms, only: [:create, :destroy]
  end
end

app/models/alarm.rb
class Alarm < ApplicationRecord
  belongs_to :region

  validates_presence_of :push_identifier, :message
  validates :seconds_before, presence: true, numericality: true

  before_validation(on: :create) do
    generate_token(:secure_token)
  end

  def to_param
    secure_token
  end

  private

  def generate_token(column)
    begin
      self[column] = SecureRandom.urlsafe_base64
    end while Alarm.exists?(column => self[column])
  end
end

app/controllers/admins/alarms_controller.rb
class Admins::AlarmsController < ApplicationController
  before_action :admin_required
  
  def index
    @region = current_admin.region
    @alarms = Alarm.order(created_at: :desc).includes(:region)
  end

  def show
    @alarm = Alarm.find(params[:id])

    server = @alarm.region.server
    key = "alarms/#{@alarm.id}/arrival_and_departure"

    @arr_dep = Rails.cache.fetch(key, expires_in: 30.seconds) do
      server.arrival_and_departure(stop_id: @alarm.stop_id, service_date: @alarm.service_date, 
                                   stop_sequence: @alarm.stop_sequence, trip_id: @alarm.trip_id, vehicle_id: @alarm.vehicle_id)
    end
  end
end

app/controllers/alarms_controller.rb
class AlarmsController < ApplicationController
  include AlarmsConcerns
  before_action :load_region
  skip_before_action :verify_authenticity_token

  def create
    create_alarm(params: params)
  end

  def destroy
    destroy_alarm_with_token(params[:id], @region)
  end

  protected

  def load_region
    @region = Region.find_by!(region_identifier: params[:region_id])
  rescue ActiveRecord::RecordNotFound
    render_not_found_response("Couldn't find Region")
  end
end

app/controllers/api/v1/alarms_controller.rb
class Api::V1::AlarmsController < Api::V1::ApiController
  include AlarmsConcerns

  def create
    record_pageview(@region, 'alarms')

    create_alarm(params: params)
  end

  def destroy
    destroy_alarm_with_token(params[:id], @region)
  end
end

app/views/admins/alarms/index.html.erb
<% title("#{@region.name} Alarms") %>
<%= render Containers::SideTabsComponent.new do |c| %>
  <%= render Admin::SideTabsComponent.new(context: c, current_path: request.fullpath) %>

  <%= render Tables::TableComponent.new do |c| %>
    <% c.with_column("ID") %>
    <% c.with_column("Region") %>
    <% c.with_column("Push ID/Message") %>
    <% c.with_column("Stop ID") %>
    <% c.with_column("Trip ID") %>
    <% c.with_column("Service Date") %>
    <% c.with_column("Vehicle ID") %>
    <% c.with_column("Stop Sequence") %>
    <% c.with_column("Created At") %>
    <% c.with_tbody do %>
      <% @alarms.each do |a| %>
        <tr>
          <td class="oba-td"><%= link_to a.id, admin_alarm_path(a.id) %></td>
          <td class="oba-td"><%= a.region.name %></td>
          <td class="oba-td">
            <%= a.message %><br>
            <%= a.push_identifier %>
          </td>
          <td class="oba-td"><%= a.stop_id %></td>
          <td class="oba-td"><%= a.trip_id %></td>
          <td class="oba-td"><%= Time.at(a.service_date / 1000.0).strftime("%m-%d-%Y") %></td>
          <td class="oba-td"><%= value_or_blank_rep(a.vehicle_id) %></td>
          <td class="oba-td"><%= a.stop_sequence %></td>
          <td class="oba-td"><%= local_time a.created_at %></td>
        </tr>
      <% end %>
    <% end %>
  <% end %>
<% end %>

app/views/admins/alarms/show.html.haml
- title "Alarm in #{@alarm.region.name}"

.row
  .col
    %table.table.table-sm.table-striped
      %thead
        %tr
          %th{colspan: "2"} Alarm Data
      %tbody
        %tr
          %td{style: 'width: 250px'} ID
          %td= @alarm.id
        %tr
          %td Created at
          %td= local_time @alarm.created_at
        %tr
          %td Region
          %td= @alarm.region.name
        %tr
          %td Push ID
          %td= @alarm.push_identifier
        %tr
          %td Message
          %td= @alarm.message
        %tr
          %td Stop ID
          %td= @alarm.stop_id
        %tr
          %td Trip ID
          %td= @alarm.trip_id
        %tr
          %td Service date
          %td= Time.at(@alarm.service_date / 1000.0).strftime("%m-%d-%Y")
        %tr
          %td Vehicle ID
          %td= value_or_blank_rep(@alarm.vehicle_id)
        %tr
          %td Stop Sequence
          %td= @alarm.stop_sequence

.row
  .col
    %table.table.table-sm.table-striped
      %thead
        %tr
          %th{colspan: "2"} Arrival/Departure
      %tbody
        %tr
          %td{style: 'width: 250px'} Name with Headsign
          %td= @arr_dep.name_with_headsign
        %tr
          %td Seconds until departure
          %td
            = @arr_dep.seconds_until_departure
        %tr
          %td Best departure time
          %td= local_time Time.at(@arr_dep.best_departure_time / 1000.0)
        %tr
          %td Current server time
          %td= local_time Time.at(@arr_dep.current_server_time / 1000.0)